import Link from "next/link";
import { AppShell } from "./components/app-shell";
import { SectionHeading } from "./components/page-primitives";
import { UserGreeting } from "./components/user-greeting";
import { UserAvatar } from "./components/user-avatar";

export default function Home() {
  return <AppShell active="/"><header className="page-header"><div><p className="eyebrow">Tuesday, September 8</p><h1><UserGreeting /></h1><p className="page-description">A little planning now makes the shop feel lighter later.</p></div><UserAvatar /></header><section className="hero-action" aria-labelledby="shopping-callout"><div><h2 id="shopping-callout">Ready to shop?</h2><p>You have 8 items waiting in your current list.</p></div><Link className="button" href="/shopping"><span aria-hidden="true">✓</span> Start shopping</Link></section><SectionHeading title="Your month at a glance" /><div className="summary-grid"><div className="surface summary-tile"><p className="summary-label">On your list</p><p className="summary-value">8</p><p className="summary-meta">2 categories</p></div><div className="surface summary-tile"><p className="summary-label">Spent this month</p><p className="summary-value">Rs. 8,420</p><p className="summary-meta">Rs. 3,500 under average</p></div></div><SectionHeading title="Smart Suggestions" link={{ href: "/recipes", label: "Explore" }} /><div className="surface recipe-card"><h3>What can you make tonight?</h3><p>Try: “I only have potatoes and onions.” Suggestions can use what you have, common pantry spices, and optional recipes needing 1–2 extra ingredients.</p><div className="recipe-card-footer"><Link href="/recipes">Get recipe ideas <span aria-hidden="true">→</span></Link><span aria-hidden="true">✦</span></div></div><SectionHeading title="Recent activity" link={{ href: "/history", label: "See history" }} /><div className="surface activity-list"><Link className="activity-row" href="/history"><span className="activity-icon" aria-hidden="true">✓</span><span className="row-copy"><h3>Weekly shop completed</h3><p>12 items · Green Valley Market</p></span><time className="row-time" dateTime="2026-09-07">Yesterday</time></Link><Link className="activity-row" href="/shopping-list"><span className="activity-icon" aria-hidden="true">＋</span><span className="row-copy"><h3>Added pantry staples</h3><p>Olive oil, rice, and garlic</p></span><time className="row-time" dateTime="2026-09-07">Mon</time></Link></div></AppShell>;
}
